[versions]
agp = "8.8.2"

# Plugin Versions
kotlin = "2.1.10"
kotlinx-datetime = "0.7.1"
androidLibrary = "7.4.2"
androidGradlePlugin = "8.13.1"
detekt = "1.23.8"

# Library Versions
androidx-activity-compose = "1.12.1"
androidx-corektx = "1.17.0"
accompanist = "0.36.0"
androidx-lifecycle = "2.10.0"
androidxHiltNavigationCompose = "1.3.0"
qr_code = "1.5.3"
timber = "5.0.1"
hilt = "2.57.2"
datastore-preferences = "1.1.1"
tv-compose-material = "1.0.1"
line_awesome = "1.0.0"
compose_bom = "2025.12.00"
media3 = "1.4.1"
media3Ui = "1.4.1"
coil = "2.7.0"
kotlin-serialisation = "1.6.0"

# Test Library Versions
junit = "4.13.2"
androidx-test-espresso = "3.6.1"
androidx-test-ext-junit = "1.2.1"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.3.3"
androidx-baselineprofile = "1.3.3"
profileinstaller = "1.4.1"
appcompat = "1.7.0"
material = "1.12.0"
ktor = "2.3.5"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-corektx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "tv-compose-material" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose_bom" }
compose-material-iconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

androidx-lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

qrcode = { module = "com.github.alexzhirkevich:custom-qr-generator", version.ref = "qr_code" }
line-awesome-icons = { module = "br.com.devsrsouza.compose.icons.android:line-awesome", version.ref = "line_awesome" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

ktor = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialisation" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.0" }

# Dep for build logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
compose-tv = ["androidx-tv-material"]
androidx-compose-bom = ["compose-material3", "compose-material-iconsExtended" , "androidx-compose-ui-tooling", "androidx-compose-ui-tooling-preview"]
compose-accompanist = ["accompanist-navigation-animation", "accompanist-placeholder"]
media3 = ["media3-exoplayer", "media3-ui"]
ktor = ["ktor", "ktor-okhttp", "ktor-serialization", "ktor-serialization-kotlinx-json", "ktor-client-content-negotiation"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibrary" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-baselineprofile" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }